import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layouts/footer";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { NavbarDemo } from "@/components/layouts/navbar";
import { Inter, Saira, Orbitron } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // or whichever weights you need
  variable: "--font-inter",
});
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"], // add weights you need
  variable: "--font-orbitron",
});

const saira = Saira({
  subsets: ["latin"],
  weight: ["400", "700"], // Add other weights if needed
  variable: "--font-saira",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${saira.variable} ${inter.variable}${orbitron.variable}`}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <Header /> */}
          <NavbarDemo />
          {children}
          <Footer />
        </ThemeProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
